[target.wasm32-unknown-unknown]
rustflags = [
  "-C", "target-feature=+bulk-memory,+mutable-globals",
  "-C", "link-arg=--max-memory=4294967296",
  "-C", "link-arg=-z", "-C", "link-arg=stack-size=8388608",
]

[unstable]
build-std = ["std", "panic_abort"]
